name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['16', '17', 'lts/*', 'node']
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: npm install
        run: npm ci
      
      - name: Lint  ${{ matrix.node-version }}
        run: npm run lint
      
      - name: Test ${{ matrix.node-version }}
        run: npm run cover-${{ matrix.node-version }}
      
      - name: Coveralls Parallel
        uses: coverallsapp/github-action@master
        with :
          github-token: ${{ secrets.GITHUB_TOKEN }}
          flag-name: run-${{ matrix.node-version }}
          parallel: true

  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
          parallel-finished: true
